#!/usr/bin/make -f

CXXFLAGS=-std=gnu++0x -O2 -g -Wall -pedantic

INCLUDES=-I$(GS_HOME)/shared/downloads/products/GemStone64Bit3.5.0-x86_64.Linux/include


LDLIBS=-lgcits-3.5.0-64
LDFLAGS=-L$(GS_HOME)/shared/downloads/products/GemStone64Bit3.5.0-x86_64.Linux/lib

CPPFLAGS:=$(CPPFLAGS) $(INCLUDES)

repl:
